// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Product struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Price     interface{} `json:"price"`
	CreatedAt interface{} `json:"created_at"`
}
