// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetProducts(ctx context.Context) ([]Product, error)
	InsertProducts(ctx context.Context, arg InsertProductsParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
