// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderProducts(ctx context.Context, arg CreateOrderProductsParams) (OrderProduct, error)
	GetProductById(ctx context.Context, id int64) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	InsertProducts(ctx context.Context, arg InsertProductsParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
